# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(20, 20, 431, 291))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("wallhaven2.png"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.img1 = QtWidgets.QPushButton(self.centralwidget)
        self.img1.setEnabled(True)
        self.img1.setGeometry(QtCore.QRect(20, 340, 221, 71))
        self.img1.setObjectName("img1")
        self.img2 = QtWidgets.QPushButton(self.centralwidget)
        self.img2.setGeometry(QtCore.QRect(240, 340, 211, 71))
        self.img2.setObjectName("img2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.img1.clicked.connect(self.show_img1)
        self.img2.clicked.connect(self.show_img2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img1.setText(_translate("MainWindow", "Wallpaper1"))
        self.img2.setText(_translate("MainWindow", "Wallpaper2"))


    def show_img1(self):
        self.Photo.setPixmap(QtGui.QPixmap("wallhaven2.png"))

    def show_img2(self):
        self.Photo.setPixmap(QtGui.QPixmap("wallpaper2.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
